project_id = "pot-and-thyme-local-validation"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = false

[inbucket]
enabled = false

[analytics]
enabled = false
